backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "ニュース" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "poster" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "広告" # Used in the UI, ie.: "New Post"
    folder: "site/content/poster" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "掲載日", name: "date", widget: "datetime"}
      - {label: "名前", name: "sponsor", widget: "string"}
      - {label: "卒業期", name: "grade", widget: "string"}
      - {label: "口数", name: "contribution", widget: "number"}
      - {label: "広告画像", name: "image", widget: "image", required: false}
      - {label: "URL", name: "link_url", widget: "string", required: false}
      - {label: "ALT", name: "alt", widget: "string", required: false}
      - {label: "メッセージ", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Summary", name: summary, widget: object, fields: [
              {label: "title", name: "title", widget: string},
              {label: "image", name: "imageUrl", widget: image}
              {label: "imageAlt", name: "imageAlt", widget: string}]}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/sponsors/_index.md"
        label: "スポンサー一覧"
        name: "sponsors"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
